#baseurl = "https://untilthecore.github.io/"
baseurl = "https://wlizhi.github.io/"
#baseurl = "http://114.55.209.178/"
title = "暗夜零星"
languageCode = "zh-Hans"
theme = "hello-friend-ng"
paginate = 20

[params]
defaultTheme = "light"
#footerLeft = "wlizhi"
#footerRight = "wlizhi"
#homeSubtitle = "hello world"
#indexData = "index-data"

[menu]

[[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 400
[[menu.main]]
    identifier = "blog"
    name = "归档"
    url = "/posts"
    weight = 300
[[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 200
[[menu.main]]
    name = "分类"
    identifier = "categories"
    url = "/categories/"
    weight = 100
#[[menu.main]]
#    parent = "分类"
#    name = "子分类1"
#    identifier = "categories"
#    url = "/categories/"
#    weight = 100

[[params.social]]
name = "email"
#url = "mailto:untilthecore@gmail.com"
url = "2456767505@qq.com"
[[params.social]]
name = "github"
url = "https://github.com/wlizhi"
[[params.social]]
name = "docker"
url = "#"

[languages.en.params.logo]
logoText = "暗夜零星"
logoCursorAnimate = "8s"
logoCursorColor = "green"
logoCursorDisabled = false
logoHomeLink = "/"

# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"